Component/filters
AlexanderStreltsov/IHelp pull request #27
Opened 2023-05-27 19:46 UTC by BobrikAU

Сделаны чекбоксы, внешняя рамка окна попапа, а также компонент фильтр.

2023-06-03 20:21 UTC, vierim commented
У фильтра есть две проблемы, которые желательно решить:

1) Фильтр не принимает никаких входных данных по уже размеченным полям. 
Предположим, что посетитель выбрал что-то в фильтре, посмотрел результаты, а потом опять вернулся в фильтр. Он не увидит то состояние фильтра, которое было в прошлый раз, а увидит состояние по дефолту. Это не совсем правильно.

2) Компонент фильтра получился очень большим, достаточно сложным и при этом немного странным. 
С одной стороны есть попытка сделать его расширяемым - это видно в типизации параметров функции sendResult. 
С другой стороны все варианты фильтра жестко задаются через type и все поля для каждого type прописаны прям JSX кодом. 

Как резюме я предлагаю стандартизировать объект, который принимает и возвращает фильтр. И я бы каждый type фильтра или каждый набор полей вынес бы в отдельные компоненты.

2023-06-03 20:24 UTC, vierim commented
![2023-06-03_23-22-30](https://github.com/AlexanderStreltsov/IHelp/assets/86350622/154e1af8-f5b2-47d9-94b1-037a35affda8)
Также прошу обратить внимание, что в FireFox есть проблема с версткой чекбоксов

2023-06-03 20:25 UTC, vierim requested changes

2023-06-03 20:25 UTC, vierim commented on src/components/filter/filter.tsx
> +  const useFilter = (e: React.SyntheticEvent<Element, Event>) => {
Не надо называть слушатель события со слова use. Любая функция, начинающаяся с use рассматривается как кастомный хук. Я сейчас точно не вспомню, это жесткое требование или просто соглашение, но все равно лучше так не делать.

2023-06-04 12:05 UTC, BobrikAU commented on src/components/filter/filter.tsx
> +  const useFilter = (e: React.SyntheticEvent<Element, Event>) => {
Исправлено

2023-06-04 18:36 UTC, vierim approved these changes

2023-06-04 18:49 UTC, merged